// src/components/Card.tsx
import React from "react";
import "../assets/style/Cards.scss";

type Link = {
  href: string;
  text: string;
};

type CardProps = {
  children?: string | React.Component[] | never[];
  title: string;
  sub?: string;
  subLinks?: Link[];
};

const generateLinks = (links: Link[]) =>
  links.map(({ href, text }, i) => (
    <h6 key={i}>
      <a href={href} key={i}>
        {text}
      </a>
    </h6>
  ));

const Card = ({ children, title, sub, subLinks }: CardProps) => (
  <div className="card-wrapper">
    <div className="card">
      <div className="title">
        <h2>{title}</h2>
        <h4>{sub}</h4>
        {subLinks !== undefined ? (
          <div className="links">{generateLinks(subLinks)}</div>
        ) : (
          ""
        )}
      </div>
      <p>{children}</p>
    </div>
  </div>
);

export default Card;

// src/components/Card.svelte
<script lang="ts">
    type CardLink = {
        href: string;
        text: string;
    };

    export let title: string;
    export let sub: string;
    export let subLinks: CardLink[];
    export let onClick: () => void;
</script>

<style lang="scss">
  @import "../node_modules/assets/style/components/Card";
</style>

<div class="card-wrapper">
    <div class="card" on:click={onClick}>
        <div class="title">
            <h2>{title}</h2>
            <h4>{sub}</h4>
            {#if (subLinks !== undefined)}
                <div class="links">
                    {#each subLinks as link}
                        <h6>
                            <a href={link.href}>
                                {link.text}
                            </a>
                        </h6>
                    {/each}
                </div>
            {/if}
        </div>
        <p>
            <slot/>
        </p>
    </div>
</div>
